import type { LevelSeed } from "./index";

export const filaSuperiorLevels: LevelSeed[] = [
  {
    slug: "fila-superior-basica",
    trackSlug: "fila-superior-e-inferior",
    order: 10,
    title: "Fila superior básica",
    description: "Practica las teclas qwerty y uiop con secuencias cortas.",
    body: "que ropa tipo euro quiero reto riqueza puro quite roque",
    minAccuracy: 92,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "fila-inferior-basica",
    trackSlug: "fila-superior-e-inferior",
    order: 20,
    title: "Fila inferior básica",
    description: "Activa los dedos en la fila zxcvbnm con palabras reales.",
    body: "zona clave banco mozo nacer brazo zinc campo vez cebra",
    minAccuracy: 92,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "superior-alterno",
    trackSlug: "fila-superior-e-inferior",
    order: 30,
    title: "Superior alterno",
    description: "Alterna fila guía y fila superior con fluidez.",
    body: "quisiera poder repetir este truco pero requiere tiempo para ello",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "inferior-alterno",
    trackSlug: "fila-superior-e-inferior",
    order: 40,
    title: "Inferior alterno",
    description: "Combina la fila inferior con la fila guía en palabras comunes.",
    body: "vez cambio blanco brazo cruce nacer vez mancha bloque buzon",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "tres-filas-mezcla",
    trackSlug: "fila-superior-e-inferior",
    order: 50,
    title: "Tres filas mezcladas",
    description: "Palabras que usan las tres filas del teclado sin preferencia.",
    body: "quizas el cerebro necesita tiempo para vincular cada movimiento",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 42,
    maxErrors: 6,
  },
  {
    slug: "patron-diagonal",
    trackSlug: "fila-superior-e-inferior",
    order: 60,
    title: "Patrón diagonal",
    description: "Secuencias que obligan al dedo a moverse en diagonal.",
    body: "breve quince zumo plomo excavar muy nexo quebrar curva boxeo",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 42,
    maxErrors: 6,
  },
  {
    slug: "palabras-mixtas",
    trackSlug: "fila-superior-e-inferior",
    order: 70,
    title: "Palabras mixtas",
    description: "Vocabulario amplio que recorre todo el teclado.",
    body: "el boxeador conquisto el primer premio con un golpe exacto y muy breve",
    minAccuracy: 95,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 44,
    maxErrors: 6,
  },
  {
    slug: "frases-tres-filas",
    trackSlug: "fila-superior-e-inferior",
    order: 80,
    title: "Frases completas",
    description: "Oraciones naturales que exigen uso de todas las filas.",
    body: "nunca es bueno correr demasiado porque el cuerpo necesita equilibrio y calma",
    minAccuracy: 95,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 5,
  },
  {
    slug: "dictado-tres-filas",
    trackSlug: "fila-superior-e-inferior",
    order: 90,
    title: "Dictado tres filas",
    description: "Dictado que cubre vocabulario de las tres filas por igual.",
    body: "el banco queda en la plaza central. cruza el puente y busca la calle nueva.",
    minAccuracy: 95,
    bronzeWpm: 26,
    silverWpm: 36,
    goldWpm: 46,
    maxErrors: 5,
  },
  {
    slug: "parrafo-tres-filas",
    trackSlug: "fila-superior-e-inferior",
    order: 100,
    title: "Párrafo de tres filas",
    description: "Párrafo que exige dominio equilibrado de todas las filas.",
    body: "un buen ejercicio es copiar textos variados que incluyan palabras con letras de todas las zonas del teclado para reforzar la memoria.",
    minAccuracy: 96,
    bronzeWpm: 28,
    silverWpm: 38,
    goldWpm: 50,
    maxErrors: 5,
  },
];
