import type { LevelSeed } from "./index";

export const fundamentosLevels: LevelSeed[] = [
  {
    slug: "fila-guia-1",
    trackSlug: "fundamentos",
    order: 10,
    title: "Fila guía I",
    description: "Activa la memoria base con letras centrales y ritmo uniforme.",
    body: "asdf jklñ asdf jklñ asa jkl asa jkl",
    minAccuracy: 92,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "fila-guia-2",
    trackSlug: "fundamentos",
    order: 20,
    title: "Fila guía II",
    description: "Refuerza la posición base alternando patrones más variados.",
    body: "falda salsa laja saldo faja dala ñala falla salda",
    minAccuracy: 92,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "palabras-cortas",
    trackSlug: "fundamentos",
    order: 30,
    title: "Palabras cortas",
    description: "Sube el ritmo manteniendo palabras fáciles y controladas.",
    body: "casa sala lado dedo mesa dato rosa sopa luna cama",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "silabas-alternas",
    trackSlug: "fundamentos",
    order: 40,
    title: "Sílabas alternas",
    description: "Practica combinaciones silábicas con ambas manos en alternancia.",
    body: "palo tema risa gota fume lodo beca nudo vela cupo",
    minAccuracy: 93,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 42,
    maxErrors: 7,
  },
  {
    slug: "frases-fluidas",
    trackSlug: "fundamentos",
    order: 50,
    title: "Frases fluidas",
    description: "Conecta frases sencillas sin romper postura ni precisión.",
    body: "la practica diaria mejora el ritmo y hace mas suave cada pulsacion",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 44,
    maxErrors: 6,
  },
  {
    slug: "frases-con-ritmo",
    trackSlug: "fundamentos",
    order: 60,
    title: "Frases con ritmo",
    description: "Escribe frases con un flujo natural y constante.",
    body: "el sol sale cada dia y las aves vuelan sobre el rio en calma",
    minAccuracy: 94,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 44,
    maxErrors: 6,
  },
  {
    slug: "signos-y-espacios",
    trackSlug: "fundamentos",
    order: 70,
    title: "Signos y espacios",
    description: "Domina comas, puntos y pausas sin perder el compás.",
    body: "respira, escribe con calma, corrige poco y sigue el ritmo final.",
    minAccuracy: 95,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 6,
  },
  {
    slug: "frases-compuestas",
    trackSlug: "fundamentos",
    order: 80,
    title: "Frases compuestas",
    description: "Une ideas cortas con conectores manteniendo la fluidez.",
    body: "escribe despacio pero sin pausa, cada letra cuenta y el ritmo crece.",
    minAccuracy: 95,
    bronzeWpm: 26,
    silverWpm: 36,
    goldWpm: 46,
    maxErrors: 5,
  },
  {
    slug: "dictado-sencillo",
    trackSlug: "fundamentos",
    order: 90,
    title: "Dictado sencillo",
    description: "Simula un dictado corto con oraciones simples y claras.",
    body: "la mesa esta en el centro de la sala. los libros estan sobre la silla.",
    minAccuracy: 95,
    bronzeWpm: 26,
    silverWpm: 36,
    goldWpm: 48,
    maxErrors: 5,
  },
  {
    slug: "parrafo-inicial",
    trackSlug: "fundamentos",
    order: 100,
    title: "Párrafo inicial",
    description: "Tu primer párrafo completo a velocidad controlada.",
    body: "un buen mecanografo no mira el teclado. sus dedos recuerdan cada tecla y su mente lee el texto sin detenerse.",
    minAccuracy: 96,
    bronzeWpm: 28,
    silverWpm: 38,
    goldWpm: 50,
    maxErrors: 5,
  },
];
