import type { LevelSeed } from "./index";

export const mayusculasLevels: LevelSeed[] = [
  {
    slug: "inicio-de-frase",
    trackSlug: "mayusculas-y-shift",
    order: 10,
    title: "Inicio de frase",
    description: "Practica la mayúscula al comienzo de cada oración.",
    body: "Hola. Buenos dias. Gracias. Cuidado. Vamos. Perfecto. Genial.",
    minAccuracy: 92,
    bronzeWpm: 16,
    silverWpm: 26,
    goldWpm: 36,
    maxErrors: 8,
  },
  {
    slug: "nombres-propios",
    trackSlug: "mayusculas-y-shift",
    order: 20,
    title: "Nombres propios",
    description: "Escribe nombres de personas y ciudades con mayúscula inicial.",
    body: "Madrid Barcelona Valencia Sevilla Carlos Maria Pedro Ana Luis Rosa",
    minAccuracy: 92,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "paises-y-ciudades",
    trackSlug: "mayusculas-y-shift",
    order: 30,
    title: "Países y ciudades",
    description: "Vocabulario geográfico con mayúsculas y minúsculas combinadas.",
    body: "Mexico es grande. Peru tiene costa. Chile es largo. Cuba tiene calor.",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "iniciales-alternas",
    trackSlug: "mayusculas-y-shift",
    order: 40,
    title: "Iniciales alternas",
    description: "Frases donde cada palabra importante empieza con mayúscula.",
    body: "El Rio Grande cruza la Frontera Norte antes de llegar al Golfo.",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "siglas-comunes",
    trackSlug: "mayusculas-y-shift",
    order: 50,
    title: "Siglas comunes",
    description: "Practica con siglas y abreviaciones en mayúscula.",
    body: "La ONU y la OMS trabajan con la UNESCO. El FBI colabora con la CIA.",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 42,
    maxErrors: 7,
  },
  {
    slug: "oraciones-formales",
    trackSlug: "mayusculas-y-shift",
    order: 60,
    title: "Oraciones formales",
    description: "Escritura formal con uso correcto de mayúsculas.",
    body: "Estimado Sr. Garcia: Le escribo para confirmar la reunion del Lunes.",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 44,
    maxErrors: 6,
  },
  {
    slug: "titulos-y-encabezados",
    trackSlug: "mayusculas-y-shift",
    order: 70,
    title: "Títulos y encabezados",
    description: "Practica escribiendo títulos con múltiples mayúsculas.",
    body: "Guia Rapida de Escritura. Manual de Buenas Practicas. Plan General.",
    minAccuracy: 95,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 44,
    maxErrors: 6,
  },
  {
    slug: "mezcla-libre",
    trackSlug: "mayusculas-y-shift",
    order: 80,
    title: "Mezcla libre",
    description: "Texto con uso variado de mayúsculas en contextos naturales.",
    body: "Juan viajo a Roma en Enero. Sofia prefiere Paris en Primavera.",
    minAccuracy: 95,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 5,
  },
  {
    slug: "dictado-formal",
    trackSlug: "mayusculas-y-shift",
    order: 90,
    title: "Dictado formal",
    description: "Dictado con nombres, lugares y fórmulas de cortesía.",
    body: "Buenos dias, Sra. Lopez. La reunion en la Sala Norte sera a las Tres.",
    minAccuracy: 95,
    bronzeWpm: 26,
    silverWpm: 36,
    goldWpm: 46,
    maxErrors: 5,
  },
  {
    slug: "parrafo-con-mayusculas",
    trackSlug: "mayusculas-y-shift",
    order: 100,
    title: "Párrafo con mayúsculas",
    description: "Párrafo extenso con uso frecuente y variado de mayúsculas.",
    body: "El Profesor Martinez viajo a Buenos Aires con la Dra. Ruiz. Visitaron el Museo Nacional y la Universidad de San Martin durante Febrero.",
    minAccuracy: 96,
    bronzeWpm: 28,
    silverWpm: 38,
    goldWpm: 50,
    maxErrors: 5,
  },
];
