import type { LevelSeed } from "./index";

export const numerosLevels: LevelSeed[] = [
  {
    slug: "numeros-basicos",
    trackSlug: "numeros-y-simbolos",
    order: 10,
    title: "Números básicos",
    description: "Practica los dígitos del 0 al 9 en secuencias simples.",
    body: "1234567890 0987654321 1029384756 5647382910",
    minAccuracy: 90,
    bronzeWpm: 14,
    silverWpm: 22,
    goldWpm: 32,
    maxErrors: 10,
  },
  {
    slug: "numeros-en-contexto",
    trackSlug: "numeros-y-simbolos",
    order: 20,
    title: "Números en contexto",
    description: "Mezcla números con palabras en situaciones cotidianas.",
    body: "tengo 3 gatos y 2 perros. vivo en el piso 5. son las 8 en punto.",
    minAccuracy: 91,
    bronzeWpm: 16,
    silverWpm: 26,
    goldWpm: 36,
    maxErrors: 9,
  },
  {
    slug: "fechas-y-horas",
    trackSlug: "numeros-y-simbolos",
    order: 30,
    title: "Fechas y horas",
    description: "Escribe fechas, horas y formatos temporales comunes.",
    body: "12/03/2025 14:30 01-01-2000 23:59 15/08/1990 09:15 31/12/2024",
    minAccuracy: 91,
    bronzeWpm: 16,
    silverWpm: 26,
    goldWpm: 36,
    maxErrors: 9,
  },
  {
    slug: "cantidades-y-precios",
    trackSlug: "numeros-y-simbolos",
    order: 40,
    title: "Cantidades y precios",
    description: "Números con símbolos monetarios y decimales.",
    body: "$19.99 $45.50 $100.00 $3.75 $999.99 $12.00 $0.50 $250.00",
    minAccuracy: 92,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "porcentajes-y-medidas",
    trackSlug: "numeros-y-simbolos",
    order: 50,
    title: "Porcentajes y medidas",
    description: "Símbolos de porcentaje y unidades de medida.",
    body: "50% de descuento. 22 grados de temperatura. 100kg de peso. 1.75m de alto.",
    minAccuracy: 92,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "operaciones-basicas",
    trackSlug: "numeros-y-simbolos",
    order: 60,
    title: "Operaciones básicas",
    description: "Símbolos aritméticos en expresiones simples.",
    body: "2 + 3 = 5. 10 - 4 = 6. 7 * 8 = 56. 100 / 4 = 25. 9 + 1 = 10.",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "simbolos-especiales",
    trackSlug: "numeros-y-simbolos",
    order: 70,
    title: "Símbolos especiales",
    description: "Practica @, #, & y otros símbolos comunes.",
    body: "email@correo.com #hashtag & empresa 50% @usuario #tema2025",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "datos-tabulares",
    trackSlug: "numeros-y-simbolos",
    order: 80,
    title: "Datos tabulares",
    description: "Simula entrada de datos con números y separadores.",
    body: "id: 001, nombre: Ana, edad: 28; id: 002, nombre: Luis, edad: 34",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 42,
    maxErrors: 6,
  },
  {
    slug: "factura-simulada",
    trackSlug: "numeros-y-simbolos",
    order: 90,
    title: "Factura simulada",
    description: "Texto que simula una factura con precios y cantidades.",
    body: "Art. 1: Teclado x2 = $59.98. Art. 2: Raton x1 = $24.99. Total: $84.97",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 44,
    maxErrors: 6,
  },
  {
    slug: "mezcla-total-numeros",
    trackSlug: "numeros-y-simbolos",
    order: 100,
    title: "Mezcla total",
    description: "Párrafo con números, símbolos y texto en contexto real.",
    body: "El vuelo SA-4521 sale a las 16:45 del 23/04. Costo: $350.00 (50% con codigo #PROMO). Contacto: info@viajes.com",
    minAccuracy: 95,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 5,
  },
];
