import type { LevelSeed } from "./index";

export const palabrasLargasLevels: LevelSeed[] = [
  {
    slug: "cuatro-silabas",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 10,
    title: "Cuatro sílabas",
    description: "Palabras de cuatro sílabas para estirar los dedos.",
    body: "mariposa caballero cocodrilo ventilador computadora television",
    minAccuracy: 92,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "cinco-silabas",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 20,
    title: "Cinco sílabas",
    description: "Palabras más largas que exigen coordinación sostenida.",
    body: "administracion comunicacion establecimiento responsabilidad",
    minAccuracy: 92,
    bronzeWpm: 16,
    silverWpm: 26,
    goldWpm: 36,
    maxErrors: 8,
  },
  {
    slug: "vocabulario-cientifico",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 30,
    title: "Vocabulario científico",
    description: "Términos del ámbito científico y académico.",
    body: "fotosintesis metabolismo ecosistema biodiversidad microorganismo",
    minAccuracy: 93,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 7,
  },
  {
    slug: "vocabulario-juridico",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 40,
    title: "Vocabulario jurídico",
    description: "Palabras del ámbito legal y administrativo.",
    body: "jurisprudencia inconstitucionalidad indemnizacion reglamentacion",
    minAccuracy: 93,
    bronzeWpm: 16,
    silverWpm: 26,
    goldWpm: 36,
    maxErrors: 7,
  },
  {
    slug: "vocabulario-medico",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 50,
    title: "Vocabulario médico",
    description: "Terminología médica común en español.",
    body: "electrocardiograma otorrinolaringologia gastroenterologia",
    minAccuracy: 93,
    bronzeWpm: 14,
    silverWpm: 24,
    goldWpm: 34,
    maxErrors: 8,
  },
  {
    slug: "prefijos-y-sufijos",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 60,
    title: "Prefijos y sufijos",
    description: "Practica con palabras que usan prefijos y sufijos comunes.",
    body: "desafortunadamente incomprensiblemente extraordinariamente",
    minAccuracy: 94,
    bronzeWpm: 16,
    silverWpm: 26,
    goldWpm: 36,
    maxErrors: 7,
  },
  {
    slug: "palabras-compuestas",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 70,
    title: "Palabras compuestas",
    description: "Palabras compuestas del español.",
    body: "rascacielos sacapuntas parabrisas guardaespaldas cortafuegos",
    minAccuracy: 94,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 7,
  },
  {
    slug: "frases-tecnicas",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 80,
    title: "Frases técnicas",
    description: "Oraciones con vocabulario especializado variado.",
    body: "la biodiversidad del ecosistema depende de la fotosintesis y el metabolismo celular de cada microorganismo presente.",
    minAccuracy: 94,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 42,
    maxErrors: 6,
  },
  {
    slug: "refranes-espanoles",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 90,
    title: "Refranes españoles",
    description: "Refranes y dichos populares con vocabulario rico.",
    body: "a caballo regalado no le mires el diente. mas vale pajaro en mano que ciento volando. quien mucho abarca poco aprieta.",
    minAccuracy: 95,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 44,
    maxErrors: 6,
  },
  {
    slug: "parrafo-vocabulario",
    trackSlug: "palabras-largas-y-vocabulario",
    order: 100,
    title: "Párrafo de vocabulario",
    description: "Párrafo extenso con vocabulario avanzado y variado.",
    body: "la responsabilidad medioambiental requiere que las organizaciones internacionales implementen estrategias extraordinarias de conservacion y reforestacion.",
    minAccuracy: 95,
    bronzeWpm: 22,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 5,
  },
];
