import type { LevelSeed } from "./index";

export const programacionLevels: LevelSeed[] = [
  {
    slug: "llaves-y-parentesis",
    trackSlug: "programacion",
    order: 10,
    title: "Llaves y paréntesis",
    description: "Los agrupadores más usados en código.",
    body: "{ } ( ) { } ( ) {{ }} (( )) {( )} ({ }) { ( ) }",
    minAccuracy: 88,
    bronzeWpm: 12,
    silverWpm: 20,
    goldWpm: 30,
    maxErrors: 12,
  },
  {
    slug: "corchetes-y-punto-coma",
    trackSlug: "programacion",
    order: 20,
    title: "Corchetes y punto y coma",
    description: "Arrays y finales de línea en sintaxis típica.",
    body: "[0, 1, 2]; [true, false]; [\"a\", \"b\"]; let x = []; arr[0];",
    minAccuracy: 89,
    bronzeWpm: 14,
    silverWpm: 22,
    goldWpm: 32,
    maxErrors: 10,
  },
  {
    slug: "operadores-basicos",
    trackSlug: "programacion",
    order: 30,
    title: "Operadores básicos",
    description: "Operadores de asignación, comparación e igualdad.",
    body: "x = 5; y == 10; z != 0; a >= b; c <= d; e === f; g !== h;",
    minAccuracy: 89,
    bronzeWpm: 14,
    silverWpm: 22,
    goldWpm: 32,
    maxErrors: 10,
  },
  {
    slug: "operadores-logicos",
    trackSlug: "programacion",
    order: 40,
    title: "Operadores lógicos",
    description: "Operadores lógicos y ternarios de programación.",
    body: "a && b; c || d; !flag; x > 0 ? \"si\" : \"no\"; a ?? b;",
    minAccuracy: 90,
    bronzeWpm: 16,
    silverWpm: 24,
    goldWpm: 34,
    maxErrors: 9,
  },
  {
    slug: "variables-y-tipos",
    trackSlug: "programacion",
    order: 50,
    title: "Variables y tipos",
    description: "Declaraciones de variables en sintaxis moderna.",
    body: "const name = \"Ana\"; let count = 0; var total = 99.5; const active = true;",
    minAccuracy: 90,
    bronzeWpm: 16,
    silverWpm: 26,
    goldWpm: 36,
    maxErrors: 9,
  },
  {
    slug: "funciones-simples",
    trackSlug: "programacion",
    order: 60,
    title: "Funciones simples",
    description: "Declaraciones de funciones con parámetros y retorno.",
    body: "function sum(a, b) { return a + b; } const greet = (name) => \"hola \" + name;",
    minAccuracy: 91,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "condicionales",
    trackSlug: "programacion",
    order: 70,
    title: "Condicionales",
    description: "Estructuras if/else y switch en código.",
    body: "if (x > 0) { console.log(\"positivo\"); } else { console.log(\"negativo\"); }",
    minAccuracy: 91,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "bucles",
    trackSlug: "programacion",
    order: 80,
    title: "Bucles",
    description: "Estructura de bucles for y while típicos.",
    body: "for (let i = 0; i < 10; i++) { arr.push(i); } while (n > 0) { n--; }",
    minAccuracy: 92,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "objetos-y-clases",
    trackSlug: "programacion",
    order: 90,
    title: "Objetos y clases",
    description: "Sintaxis de objetos, clases y métodos.",
    body: "const user = { name: \"Luis\", age: 30 }; class App { constructor() { this.init(); } }",
    minAccuracy: 92,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "codigo-realista",
    trackSlug: "programacion",
    order: 100,
    title: "Código realista",
    description: "Fragmento de código completo y funcional.",
    body: "async function fetchData(url) { const res = await fetch(url); if (!res.ok) { throw new Error(\"fallo\"); } return res.json(); }",
    minAccuracy: 93,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 44,
    maxErrors: 7,
  },
  {
    slug: "typescript-tipos",
    trackSlug: "programacion",
    order: 110,
    title: "TypeScript tipos",
    description: "Anotaciones de tipo y genéricos de TypeScript.",
    body: "type User = { id: number; name: string; }; function get<T>(key: string): T | null { return null; }",
    minAccuracy: 93,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 44,
    maxErrors: 7,
  },
  {
    slug: "sql-basico",
    trackSlug: "programacion",
    order: 120,
    title: "SQL básico",
    description: "Consultas SQL comunes con sintaxis precisa.",
    body: "SELECT id, name FROM users WHERE active = true ORDER BY name ASC LIMIT 10;",
    minAccuracy: 93,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 44,
    maxErrors: 7,
  },
];
