import type { LevelSeed } from "./index";

export const puntuacionLevels: LevelSeed[] = [
  {
    slug: "coma-y-punto",
    trackSlug: "puntuacion-avanzada",
    order: 10,
    title: "Coma y punto",
    description: "Repasa los signos más básicos en contextos variados.",
    body: "hoy, mañana y pasado. uno, dos, tres. llueve, pero saldré.",
    minAccuracy: 92,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "punto-y-coma",
    trackSlug: "puntuacion-avanzada",
    order: 20,
    title: "Punto y coma",
    description: "Practica el uso correcto del punto y coma en enumeraciones.",
    body: "trajo libros; compró tinta; envió cartas; cerró la oficina al final.",
    minAccuracy: 92,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "dos-puntos",
    trackSlug: "puntuacion-avanzada",
    order: 30,
    title: "Dos puntos",
    description: "Los dos puntos antes de listas, citas y explicaciones.",
    body: "necesito lo siguiente: papel, lapiz, goma y regla. nota: todo urgente.",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "signos-interrogacion",
    trackSlug: "puntuacion-avanzada",
    order: 40,
    title: "Signos de interrogación",
    description: "Preguntas con apertura y cierre en español.",
    body: "¿Vienes hoy? ¿Tienes tiempo? ¿Sabes la respuesta? ¿Cuándo empieza?",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "signos-exclamacion",
    trackSlug: "puntuacion-avanzada",
    order: 50,
    title: "Signos de exclamación",
    description: "Exclamaciones con apertura y cierre al estilo español.",
    body: "¡Bravo! ¡Excelente trabajo! ¡No puedo creerlo! ¡Vamos a ganar!",
    minAccuracy: 93,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "comillas-y-guion",
    trackSlug: "puntuacion-avanzada",
    order: 60,
    title: "Comillas y guión",
    description: "Practica comillas dobles, simples y guiones en diálogos.",
    body: "dijo: \"no vengas\". ella respondió: \"ya veremos\". el resultado fue claro.",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 42,
    maxErrors: 6,
  },
  {
    slug: "parentesis-y-corchetes",
    trackSlug: "puntuacion-avanzada",
    order: 70,
    title: "Paréntesis y corchetes",
    description: "Uso de agrupadores en textos explicativos.",
    body: "el autor (nacido en 1980) publicó su obra [primera edición] en Madrid.",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 42,
    maxErrors: 6,
  },
  {
    slug: "puntos-suspensivos",
    trackSlug: "puntuacion-avanzada",
    order: 80,
    title: "Puntos suspensivos",
    description: "Practica la elipsis y las pausas dramáticas.",
    body: "tal vez... no estoy seguro... pero creo que... si, es correcto.",
    minAccuracy: 94,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 44,
    maxErrors: 6,
  },
  {
    slug: "mezcla-de-signos",
    trackSlug: "puntuacion-avanzada",
    order: 90,
    title: "Mezcla de signos",
    description: "Combina todos los signos de puntuación en frases reales.",
    body: "¿De verdad? ¡No me digas! \"Es increíble\", dijo (con sorpresa); luego calló.",
    minAccuracy: 95,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 5,
  },
  {
    slug: "parrafo-puntuado",
    trackSlug: "puntuacion-avanzada",
    order: 100,
    title: "Párrafo bien puntuado",
    description: "Párrafo con uso intensivo y correcto de toda la puntuación.",
    body: "María preguntó: \"¿Cuándo llegará?\". Juan respondió: \"¡Mañana!\". Ella asintió; no dijo nada más... solo esperó (en silencio).",
    minAccuracy: 95,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 5,
  },
];
