import type { LevelSeed } from "./index";

export const textosRealesLevels: LevelSeed[] = [
  {
    slug: "noticia-corta",
    trackSlug: "textos-reales",
    order: 10,
    title: "Noticia corta",
    description: "Fragmento de estilo periodístico breve.",
    body: "el gobierno anuncio nuevas medidas para impulsar la economia digital y facilitar el acceso a internet en zonas rurales del pais.",
    minAccuracy: 93,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 6,
  },
  {
    slug: "cronica-deportiva",
    trackSlug: "textos-reales",
    order: 20,
    title: "Crónica deportiva",
    description: "Texto con estilo de crónica de deportes.",
    body: "el equipo local gano por tres goles a uno en un partido intenso. el delantero marco dos tantos en la segunda mitad.",
    minAccuracy: 93,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 6,
  },
  {
    slug: "receta-de-cocina",
    trackSlug: "textos-reales",
    order: 30,
    title: "Receta de cocina",
    description: "Instrucciones culinarias con vocabulario de cocina.",
    body: "corta las cebollas en rodajas finas. calienta el aceite en una sarten grande. anade las cebollas y cocina a fuego lento durante veinte minutos.",
    minAccuracy: 93,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 44,
    maxErrors: 7,
  },
  {
    slug: "resena-literaria",
    trackSlug: "textos-reales",
    order: 40,
    title: "Reseña literaria",
    description: "Texto crítico sobre una obra de ficción.",
    body: "la novela presenta una trama compleja con personajes profundos que reflejan los dilemas morales de la sociedad contemporanea. el autor logra un equilibrio notable entre accion y reflexion.",
    minAccuracy: 94,
    bronzeWpm: 26,
    silverWpm: 36,
    goldWpm: 48,
    maxErrors: 7,
  },
  {
    slug: "articulo-cientifico",
    trackSlug: "textos-reales",
    order: 50,
    title: "Artículo científico",
    description: "Fragmento con vocabulario científico divulgativo.",
    body: "las celulas madre tienen la capacidad de diferenciarse en diversos tipos de tejidos. esta propiedad las convierte en una herramienta clave para la medicina regenerativa actual.",
    minAccuracy: 94,
    bronzeWpm: 26,
    silverWpm: 36,
    goldWpm: 48,
    maxErrors: 7,
  },
  {
    slug: "carta-formal",
    trackSlug: "textos-reales",
    order: 60,
    title: "Carta formal",
    description: "Carta comercial con fórmulas de cortesía.",
    body: "estimado cliente, le informamos que su pedido ha sido procesado correctamente. la entrega esta programada para el proximo martes entre las nueve y las doce horas.",
    minAccuracy: 94,
    bronzeWpm: 26,
    silverWpm: 36,
    goldWpm: 48,
    maxErrors: 7,
  },
  {
    slug: "ensayo-breve",
    trackSlug: "textos-reales",
    order: 70,
    title: "Ensayo breve",
    description: "Texto argumentativo breve sobre un tema cotidiano.",
    body: "la lectura diaria no solo mejora el vocabulario, sino que tambien desarrolla la capacidad de concentracion y la empatia. quienes leen con frecuencia suelen comunicarse con mayor claridad.",
    minAccuracy: 95,
    bronzeWpm: 28,
    silverWpm: 38,
    goldWpm: 50,
    maxErrors: 7,
  },
  {
    slug: "cronica-historica",
    trackSlug: "textos-reales",
    order: 80,
    title: "Crónica histórica",
    description: "Fragmento de texto histórico divulgativo.",
    body: "durante el siglo quince, los navegantes europeos buscaron nuevas rutas hacia oriente. sus viajes transformaron el comercio mundial y establecieron contacto entre civilizaciones que hasta entonces no se conocian.",
    minAccuracy: 95,
    bronzeWpm: 28,
    silverWpm: 38,
    goldWpm: 50,
    maxErrors: 8,
  },
  {
    slug: "texto-filosofico",
    trackSlug: "textos-reales",
    order: 90,
    title: "Texto filosófico",
    description: "Fragmento reflexivo con vocabulario abstracto.",
    body: "la libertad no es la ausencia de restricciones sino la capacidad de elegir con conciencia. cada decision que tomamos define no solo nuestro presente sino tambien el horizonte de nuestras posibilidades futuras.",
    minAccuracy: 95,
    bronzeWpm: 28,
    silverWpm: 38,
    goldWpm: 50,
    maxErrors: 8,
  },
  {
    slug: "discurso-motivacional",
    trackSlug: "textos-reales",
    order: 100,
    title: "Discurso motivacional",
    description: "Texto inspirador con ritmo oratorio.",
    body: "no importa cuantas veces caigas, lo que importa es cuantas veces te levantes. la grandeza no se mide por la ausencia de fracasos sino por la determinacion de seguir adelante cuando todo parece estar en contra.",
    minAccuracy: 96,
    bronzeWpm: 30,
    silverWpm: 40,
    goldWpm: 52,
    maxErrors: 8,
  },
  {
    slug: "texto-tecnico",
    trackSlug: "textos-reales",
    order: 110,
    title: "Texto técnico",
    description: "Fragmento de manual técnico en español.",
    body: "para instalar el sistema, conecte el cable de alimentacion al puerto principal. verifique que el indicador led se encienda en color verde. luego, acceda al panel de configuracion mediante la direccion predeterminada.",
    minAccuracy: 96,
    bronzeWpm: 30,
    silverWpm: 40,
    goldWpm: 52,
    maxErrors: 8,
  },
];
