import type { LevelSeed } from "./index";

export const tildesLevels: LevelSeed[] = [
  {
    slug: "vocales-acentuadas",
    trackSlug: "tildes-y-acentos",
    order: 10,
    title: "Vocales acentuadas",
    description: "Practica cada vocal con tilde en palabras cortas.",
    body: "mamá papá café está será allí aquí menú algún según",
    minAccuracy: 90,
    bronzeWpm: 16,
    silverWpm: 24,
    goldWpm: 34,
    maxErrors: 9,
  },
  {
    slug: "agudas-comunes",
    trackSlug: "tildes-y-acentos",
    order: 20,
    title: "Agudas comunes",
    description: "Palabras agudas terminadas en vocal, n o s.",
    body: "canción razón también jardín después común salón compás además",
    minAccuracy: 90,
    bronzeWpm: 16,
    silverWpm: 26,
    goldWpm: 36,
    maxErrors: 9,
  },
  {
    slug: "graves-con-tilde",
    trackSlug: "tildes-y-acentos",
    order: 30,
    title: "Graves con tilde",
    description: "Palabras graves que llevan tilde por terminar en consonante distinta de n o s.",
    body: "árbol fácil difícil útil ágil débil cárcel azúcar hábil lápiz",
    minAccuracy: 91,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "esdrujulas",
    trackSlug: "tildes-y-acentos",
    order: 40,
    title: "Esdrújulas",
    description: "Todas las esdrújulas llevan tilde. Practica el patrón.",
    body: "música práctica técnica médico último número teléfono público sábado",
    minAccuracy: 91,
    bronzeWpm: 18,
    silverWpm: 28,
    goldWpm: 38,
    maxErrors: 8,
  },
  {
    slug: "monosilabos-con-tilde",
    trackSlug: "tildes-y-acentos",
    order: 50,
    title: "Monosílabos con tilde",
    description: "Distingue monosílabos con y sin tilde diacrítica.",
    body: "él quiere el libro. tú sabes que tu casa es grande. sé que se fue.",
    minAccuracy: 92,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "frases-con-acentos",
    trackSlug: "tildes-y-acentos",
    order: 60,
    title: "Frases con acentos",
    description: "Oraciones naturales con alta densidad de tildes.",
    body: "la canción clásica del salón sonó después de la última sesión pública.",
    minAccuracy: 92,
    bronzeWpm: 20,
    silverWpm: 30,
    goldWpm: 40,
    maxErrors: 7,
  },
  {
    slug: "interrogativas-tilde",
    trackSlug: "tildes-y-acentos",
    order: 70,
    title: "Interrogativas con tilde",
    description: "Practica los pronombres interrogativos acentuados.",
    body: "cuándo llegas dónde vives cómo estás cuánto cuesta quién viene",
    minAccuracy: 93,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 42,
    maxErrors: 6,
  },
  {
    slug: "pasado-y-futuro",
    trackSlug: "tildes-y-acentos",
    order: 80,
    title: "Pasado y futuro",
    description: "Verbos conjugados que exigen tilde en pretérito y futuro.",
    body: "estudié comió vivirá saldrán perdió escribió llegará pasarán",
    minAccuracy: 93,
    bronzeWpm: 22,
    silverWpm: 32,
    goldWpm: 42,
    maxErrors: 6,
  },
  {
    slug: "parrafo-acentuado",
    trackSlug: "tildes-y-acentos",
    order: 90,
    title: "Párrafo acentuado",
    description: "Párrafo con uso intensivo de palabras acentuadas.",
    body: "la música clásica también tiene su razón de ser. según el público, la última canción fue fantástica y única.",
    minAccuracy: 94,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 5,
  },
  {
    slug: "dictado-acentos",
    trackSlug: "tildes-y-acentos",
    order: 100,
    title: "Dictado de acentos",
    description: "Dictado completo con reglas de acentuación variadas.",
    body: "José compró un teléfono público. María pidió información después de la décima sesión. Él sabía cuánto costó.",
    minAccuracy: 94,
    bronzeWpm: 24,
    silverWpm: 34,
    goldWpm: 46,
    maxErrors: 5,
  },
  {
    slug: "desafio-tildes",
    trackSlug: "tildes-y-acentos",
    order: 110,
    title: "Desafío final de tildes",
    description: "Texto exigente con toda la variedad de acentuación del español.",
    body: "el lingüista explicó cómo la gramática histórica evolucionó según las épocas. también mencionó cuántas regiones geográficas influyeron.",
    minAccuracy: 95,
    bronzeWpm: 26,
    silverWpm: 36,
    goldWpm: 48,
    maxErrors: 5,
  },
];
