import type { LevelSeed } from "./index";

export const velocidadLevels: LevelSeed[] = [
  {
    slug: "sprint-corto",
    trackSlug: "velocidad-y-resistencia",
    order: 10,
    title: "Sprint corto",
    description: "Escribe rápido un texto breve sin perder precisión.",
    body: "el viento sopla fuerte hoy y las hojas caen de los arboles al suelo",
    minAccuracy: 93,
    bronzeWpm: 28,
    silverWpm: 38,
    goldWpm: 50,
    maxErrors: 6,
  },
  {
    slug: "sprint-medio",
    trackSlug: "velocidad-y-resistencia",
    order: 20,
    title: "Sprint medio",
    description: "Texto algo más largo manteniendo buena velocidad.",
    body: "cuando la lluvia cae sobre la ciudad, las calles brillan y la gente busca refugio en los portales mas cercanos.",
    minAccuracy: 93,
    bronzeWpm: 28,
    silverWpm: 38,
    goldWpm: 50,
    maxErrors: 6,
  },
  {
    slug: "resistencia-basica",
    trackSlug: "velocidad-y-resistencia",
    order: 30,
    title: "Resistencia básica",
    description: "Mantén un ritmo estable durante un texto de longitud media.",
    body: "aprender a escribir rapido no es solo cuestion de velocidad, sino de mantener un equilibrio constante entre la precision de cada letra y el flujo natural de las palabras.",
    minAccuracy: 93,
    bronzeWpm: 30,
    silverWpm: 40,
    goldWpm: 52,
    maxErrors: 7,
  },
  {
    slug: "resistencia-media",
    trackSlug: "velocidad-y-resistencia",
    order: 40,
    title: "Resistencia media",
    description: "Texto más largo para acostumbrar los dedos a sesiones extensas.",
    body: "la practica continua es la clave del progreso. cada dia que dedicas tiempo a mejorar tu escritura, tus dedos ganan confianza y tu cerebro automatiza los movimientos necesarios para cada tecla.",
    minAccuracy: 94,
    bronzeWpm: 30,
    silverWpm: 40,
    goldWpm: 52,
    maxErrors: 7,
  },
  {
    slug: "flujo-constante",
    trackSlug: "velocidad-y-resistencia",
    order: 50,
    title: "Flujo constante",
    description: "Escribe sin detenerte, manteniendo un ritmo uniforme.",
    body: "imagina que cada palabra es un escalon y que cada frase te acerca a la cima. no te detengas a pensar en los errores; corregir se aprende con calma, pero la velocidad se gana con practica.",
    minAccuracy: 94,
    bronzeWpm: 32,
    silverWpm: 42,
    goldWpm: 54,
    maxErrors: 7,
  },
  {
    slug: "texto-descriptivo",
    trackSlug: "velocidad-y-resistencia",
    order: 60,
    title: "Texto descriptivo",
    description: "Párrafo descriptivo que requiere concentración sostenida.",
    body: "el mercado estaba lleno de colores y aromas. los puestos de fruta ofrecian naranjas, manzanas y peras frescas. al fondo, un hombre tocaba la guitarra mientras los niños corrian entre los pasillos.",
    minAccuracy: 94,
    bronzeWpm: 32,
    silverWpm: 42,
    goldWpm: 54,
    maxErrors: 8,
  },
  {
    slug: "texto-narrativo",
    trackSlug: "velocidad-y-resistencia",
    order: 70,
    title: "Texto narrativo",
    description: "Fragmento narrativo con ritmo exigente.",
    body: "aquel viernes por la tarde, despues de cerrar la oficina, Pedro camino hasta la estacion y tomo el tren de las siete. el vagon iba casi vacio y pudo sentarse junto a la ventana para ver el atardecer.",
    minAccuracy: 95,
    bronzeWpm: 34,
    silverWpm: 44,
    goldWpm: 56,
    maxErrors: 8,
  },
  {
    slug: "parrafo-extenso",
    trackSlug: "velocidad-y-resistencia",
    order: 80,
    title: "Párrafo extenso",
    description: "Texto largo para desarrollar verdadera resistencia.",
    body: "la escritura rapida y precisa es una habilidad que se construye con paciencia. al principio, los dedos dudan y buscan cada tecla con cuidado. con el tiempo, la memoria muscular se activa y las palabras fluyen sin esfuerzo. el secreto esta en no rendirse.",
    minAccuracy: 95,
    bronzeWpm: 34,
    silverWpm: 44,
    goldWpm: 56,
    maxErrors: 9,
  },
  {
    slug: "doble-parrafo",
    trackSlug: "velocidad-y-resistencia",
    order: 90,
    title: "Doble párrafo",
    description: "Dos párrafos completos sin descanso.",
    body: "escribir bien no es un don, es una disciplina. cada sesion de practica refuerza las conexiones entre tus dedos y tu mente. no importa cuantos errores cometas al principio; lo que importa es que sigas adelante con determinacion y constancia cada dia.",
    minAccuracy: 95,
    bronzeWpm: 36,
    silverWpm: 46,
    goldWpm: 58,
    maxErrors: 9,
  },
  {
    slug: "maraton-final",
    trackSlug: "velocidad-y-resistencia",
    order: 100,
    title: "Maratón final",
    description: "El texto más largo y exigente del track para medir tu resistencia real.",
    body: "dicen que la paciencia es la madre de todas las virtudes. en el camino de aprender a escribir con rapidez y precision, cada minuto invertido suma valor. los grandes mecanografos del pasado entrenaban horas al dia con textos largos y variados. hoy tienes herramientas mejores, pero el esfuerzo sigue siendo el mismo: constancia, ritmo y concentracion.",
    minAccuracy: 96,
    bronzeWpm: 36,
    silverWpm: 48,
    goldWpm: 60,
    maxErrors: 10,
  },
];
